package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// writeDocsNav generates a .pages file (read by mkdocs-awesome-pages) that
// groups the generated command pages by verb, so the site navigation and the
// llms.txt derived from it get one section per verb instead of a flat list.
func writeDocsNav(dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}

	// pages maps a top-level command name to its pages, e.g.
	// "add" -> [lagoon_add.md, lagoon_add_deploytarget.md, ...].
	pages := map[string][]string{}
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".md") || name == "lagoon.md" {
			continue
		}
		parts := strings.SplitN(strings.TrimSuffix(name, ".md"), "_", 3)
		if len(parts) < 2 {
			continue
		}
		pages[parts[1]] = append(pages[parts[1]], name)
	}

	commands := make([]string, 0, len(pages))
	for command := range pages {
		commands = append(commands, command)
	}
	sort.Strings(commands)

	var nav strings.Builder
	nav.WriteString("# Generated by `lagoon --docs` (make docs); do not edit by hand.\n")
	nav.WriteString("title: Commands\n")
	nav.WriteString("nav:\n")
	nav.WriteString("  - lagoon.md\n")
	for _, command := range commands {
		sort.Strings(pages[command])
		if len(pages[command]) == 1 {
			fmt.Fprintf(&nav, "  - %s\n", pages[command][0])
			continue
		}
		fmt.Fprintf(&nav, "  - %s:\n", strings.ToUpper(command[:1])+command[1:])
		for _, page := range pages[command] {
			fmt.Fprintf(&nav, "      - %s\n", page)
		}
	}

	return os.WriteFile(filepath.Join(dir, ".pages"), []byte(nav.String()), 0644)
}
